# Generated by Django 2.1.7 on 2019-09-25 03:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20190924_2359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='created_at',
            field=models.DateField(blank=True, default=datetime.datetime(2019, 9, 25, 0, 6, 28, 483856)),
        ),
    ]
